//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crudular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LitsEntities : DbContext
    {
        public LitsEntities()
            : base("name=LitsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<Freezer> Freezers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<NIHUser> NIHUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ItemLocation> ItemLocations { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
