//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crudular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freezer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freezer()
        {
            this.Boxes = new HashSet<Box>();
        }
    
        public int FreezerID { get; set; }
        public int LabID { get; set; }
        public string FreezerName { get; set; }
        public string FreezerLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual Lab Lab { get; set; }
    }
}
